export const FONTS = [
  { label: '預設字體', value: '' },
  { label: '思源黑體', value: 'SourceHanSans' },
  { label: '思源宋體', value: 'SourceHanSerif' },
  { label: '方正黑體', value: 'FangZhengHeiTi' },
  { label: '方正楷體', value: 'FangZhengKaiTi' },
  { label: '方正宋體', value: 'FangZhengShuSong' },
  { label: '方正仿宋', value: 'FangZhengFangSong' },
  { label: '阿里巴巴普惠體', value: 'AlibabaPuHuiTi' },
  { label: '朱雀仿宋', value: 'ZhuqueFangSong' },
  { label: '霞蔚文楷', value: 'LXGWWenKai' },
  { label: '文鼎PL楷體', value: 'WenDingPLKaiTi' },
  { label: '得意黑', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: '倉耳小丸子', value: 'CangerXiaowanzi' },
  { label: '優設標題黑', value: 'YousheTitleBlack' },
  { label: '峰廣明銳體', value: 'FengguangMingrui' },
  { label: '攝圖摩登小方體', value: 'ShetuModernSquare' },
  { label: '站酷快樂體', value: 'ZcoolHappy' },
  { label: '字製區喜脈體', value: 'ZizhiQuXiMai' },
  { label: '素材集市康康體', value: 'SucaiJishiKangkang' },
  { label: '素材集市酷方體', value: 'SucaiJishiCoolSquare' },
  { label: '途牛類圓體', value: 'TuniuRounded' },
  { label: '銳字真言體', value: 'RuiziZhenyan' },
]